FLAGS:=-g -O0
OUT:=-o test_analysis.elf
FILES:=test_analysis.c analysis.c analysis.h conditions.h commands.h ../parser/parser.h ../parser/parser.c

all: analysis

analysis:
	gcc $(FLAGS) $(FILES) $(OUT)
